"""Add is_opted_out to Belong table

Revision ID: 3ee64a9b7b2a
Revises: ac46f6834c2b
Create Date: 2021-12-08 10:30:55.775851

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3ee64a9b7b2a"
down_revision = "ac46f6834c2b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "belongs",
        sa.Column("is_opted_out", sa.Boolean(), server_default="f", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("belongs", "is_opted_out")
    # ### end Alembic commands ###
