"""Add difficulty to QuestionRecord

Revision ID: c4d6c4365a96
Revises: 67d857eefa28
Create Date: 2021-05-02 19:37:42.312116

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c4d6c4365a96"
down_revision = "67d857eefa28"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question_records", sa.Column("difficulty", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question_records", "difficulty")
    # ### end Alembic commands ###
