"""Add started_at to InterviewPairs table

Revision ID: 60fa87b77866
Revises: 3a00923efd42
Create Date: 2021-05-03 00:09:45.866435

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "60fa87b77866"
down_revision = "3a00923efd42"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interview_pairs",
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interview_pairs", "started_at")
    # ### end Alembic commands ###
