"""Add update cascades

Revision ID: ac46f6834c2b
Revises: a8271c222460
Create Date: 2021-05-05 15:40:52.276184

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "ac46f6834c2b"
down_revision = "a8271c222460"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("belongs_chat_id_fkey", "belongs", type_="foreignkey")
    op.drop_constraint("belongs_user_id_fkey", "belongs", type_="foreignkey")
    op.create_foreign_key(
        None,
        "belongs",
        "chats",
        ["chat_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "belongs",
        "users",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "interview_pairs_user_one_id_fkey", "interview_pairs", type_="foreignkey"
    )
    op.drop_constraint(
        "interview_pairs_chat_id_fkey", "interview_pairs", type_="foreignkey"
    )
    op.drop_constraint(
        "interview_pairs_user_two_id_fkey", "interview_pairs", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "interview_pairs",
        "users",
        ["user_two_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "interview_pairs",
        "users",
        ["user_one_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "interview_pairs",
        "chats",
        ["chat_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "question_records_user_id_fkey", "question_records", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "question_records",
        "users",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "question_records", type_="foreignkey")
    op.create_foreign_key(
        "question_records_user_id_fkey",
        "question_records",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "interview_pairs", type_="foreignkey")
    op.drop_constraint(None, "interview_pairs", type_="foreignkey")
    op.drop_constraint(None, "interview_pairs", type_="foreignkey")
    op.create_foreign_key(
        "interview_pairs_user_two_id_fkey",
        "interview_pairs",
        "users",
        ["user_two_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "interview_pairs_chat_id_fkey",
        "interview_pairs",
        "chats",
        ["chat_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "interview_pairs_user_one_id_fkey",
        "interview_pairs",
        "users",
        ["user_one_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "belongs", type_="foreignkey")
    op.drop_constraint(None, "belongs", type_="foreignkey")
    op.create_foreign_key(
        "belongs_user_id_fkey",
        "belongs",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "belongs_chat_id_fkey",
        "belongs",
        "chats",
        ["chat_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
