"""Add chat_id to InterviewPairs table

Revision ID: a8271c222460
Revises: 60fa87b77866
Create Date: 2021-05-03 00:18:25.022360

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "a8271c222460"
down_revision = "60fa87b77866"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interview_pairs", sa.Column("chat_id", postgresql.UUID(), nullable=False)
    )
    op.create_foreign_key(
        None, "interview_pairs", "chats", ["chat_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "interview_pairs", type_="foreignkey")
    op.drop_column("interview_pairs", "chat_id")
    # ### end Alembic commands ###
