"""Add username to User table

Revision ID: c155cf8d5459
Revises: 3ee64a9b7b2a
Create Date: 2022-08-14 23:38:01.817762

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c155cf8d5459"
down_revision = "3ee64a9b7b2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(), nullable=True))
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
