"""Separate opting out into two columns

Revision ID: afed5389b571
Revises: c155cf8d5459
Create Date: 2022-08-14 23:48:34.724764

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "afed5389b571"
down_revision = "c155cf8d5459"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "belongs",
        sa.Column(
            "is_opted_out_of_questions",
            sa.Boolean(),
            server_default="f",
            nullable=False,
        ),
    )
    op.add_column(
        "belongs",
        sa.Column(
            "is_opted_out_of_interviews",
            sa.Boolean(),
            server_default="f",
            nullable=False,
        ),
    )
    op.execute(
        "UPDATE belongs SET is_opted_out_of_questions = TRUE, is_opted_out_of_interviews = TRUE WHERE is_opted_out = TRUE"
    )
    op.drop_column("belongs", "is_opted_out")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "belongs",
        sa.Column(
            "is_opted_out",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.execute(
        "UPDATE belongs SET is_opted_out = TRUE WHERE is_opted_out_of_questions = TRUE AND is_opted_out_of_interviews = TRUE"
    )
    op.drop_column("belongs", "is_opted_out_of_interviews")
    op.drop_column("belongs", "is_opted_out_of_questions")
    # ### end Alembic commands ###
